#!/bin/bash

# connect to utopia
#curl uto.pia/login
# nmcli d wifi connect <essid> password <pass>
# nmcli d wifi connect <essid> --ask

# ssh with automatic vpn on-off
# usage: qssh <hostname>
qssh () {
    local host=${1:-"portokali"}

    vpn_on
    sleep 2
    echo "connecting..."
    sleep 2
    ssh "${host}"
    vpn_off
}

# display weather report
# usage: weather <city name> <style of output> 
weather () {
	local city=${1:-"ηρακλειο"}
	local style=${2:-1}

    curl v${style}.wttr.in/${city}
}

# going up directories n times
# usage: up <n>
up () {
    local d=""
    local limit="${1:-1}"

    # Default to limit of 1
    [ "$limit" -le 0 ] && limit=1
    
    for ((i=1;i<=limit;i++)); do
        d="../$d"
    done
    
    # perform cd. Show error if cd fails
    ! cd "$d" && echo "Couldn't go up $limit dirs.";
}

# extract any archive
# usage: extract <file>
extract () {
	if [ ! -f "$1" ]; then
		echo "'$1' is not a valid file"
		return
	fi

	case $1 in
		*.tar.bz2) tar xjf $1      ;;
		*.tar.gz)  tar xzf $1      ;;
		*.bz2)     bunzip2 $1      ;;
		*.rar)     unrar-free x $1 ;;
		*.gz)      gunzip $1       ;;
		*.tar)     tar xf $1       ;;
		*.tbz2)    tar xjf $1      ;;
		*.tgz)     tar xzf $1      ;;
		*.zip)     unzip $1        ;;
		*.Z)       uncompress $1   ;;
		*.7z)      7z x $1         ;;
		*.deb)     ar x $1         ;;
		*.tar.xz)  tar xf $1       ;;
		*.tar.zst) unzstd $1       ;;
		*)         echo "'$1' cannot be extracted via ex()" ;;
	esac
}
