#!/bin/bash

# Color definitions (taken from Color Bash Prompt HowTo).
# Some colors might look different of some terminals.

# Foreground
Black='\[\e[0;30m\]'
Red='\[\e[0;31m\]'
Green='\[\e[0;32m\]'
Yellow='\[\e[0;33m\]'
Blue='\[\e[0;34m\]'
Purple='\[\e[0;35m\]'
Cyan='\[\e[0;36m\]'
White='\[\e[0;37m\]'

# Bold
Bold_Black='\[\e[1;30m\]'
Bold_Red='\[\e[1;31m\]'
Bold_Green='\[\e[1;32m\]'
Bold_Yellow='\[\e[1;33m\]'
Bold_Blue='\[\e[1;34m\]'
Bold_Purple='\[\e[1;35m\]'
Bold_Cyan='\[\e[1;36m\]'
Bold_White='\[\e[1;37m\]'

# Background
On_Black='\[\e[40m\]'
On_Red='\[\e[41m\]'
On_Green='\[\e[42m\]'
On_Yellow='\[\e[43m\]'
On_Blue='\[\e[44m\]'
On_Purple='\[\e[45m\]'
On_Cyan='\[\e[46m\]'
On_White='\[\e[47m\]'

Reset='\[\e[0m\]'
