#!/bin/bash

# prompt string: [user@host path]$

git_prompt () {
    local branch="$(git symbolic-ref HEAD 2>/dev/null | cut -d'/' -f3-)"
    local branch_truncated="${branch:0:30}"

    if (( ${#branch} > ${#branch_truncated} )); then
        branch="${branch_truncated}..."
    fi

    [ -n "${branch}" ] && echo " ( ${branch}) "
}

# read bash_colors file
if [ -f "${BASH_CONFIG_FILES}bash_colors" ]; then
	. "${BASH_CONFIG_FILES}bash_colors"

    #PS1="${Bold_Blue}[${Bold_Red}\u@\h ${Bold_Blue}\W]${White}\$ ${Reset}"

    # inspired by this prompt: https://github.com/mathiasbynens/dotfiles
    # FIX: on appears everytime
    #
    # PS1=" ${Bold_Red}\u${White} at ${Bold_Blue}\h${White} in ${Bold_Green}\W"
    # PS1+="${White} on"
    # PS1+="${Bold_Cyan}\$(git_prompt)\n"
    # PS1+=" ${Bold_Yellow}> "
    # PS1+="${Reset}"

    PS1="${Bold_Blue}["
    PS1+="${Bold_Red}\u@\h "
    PS1+="${Bold_Blue}\W"
    PS1+="${Bold_Cyan}\$(git_prompt)"
    PS1+="${Bold_Blue}]"
    PS1+="${White}\$ "
    PS1+="${Reset}"
else
	PS1="[\u@\h \W]\$ "
fi
